### ISSUE TITLE
Remove extra space below tables

### ISSUE THREAD

**Issue by wrenaria** [UCDavisLibrary/ucdlib-theme-wp#101]
There appears to be a lot of extra empty space at the bottom of tables which makes for some weird visual formatting on a number of pages. Is this something that can be adjusted? I included a screenshot below of a table selected so you can more easily see where the extra space lies.

![Screen Shot 2022-05-11 at 9 35 32 AM](https://user-images.githubusercontent.com/17831969/167902320-b3648015-3096-4985-8a9b-dbdfa532d960.png)

**Comment by spelkey-ucd** [comment]
https://sandbox.library.ucdavis.edu/bug-fixes/#table-spacing

**Comment by wrenaria** [comment]
Looks good!
