### ISSUE TITLE
Decrease space between icon panel header and content

### ISSUE THREAD

**Issue by wrenaria** [UCDavisLibrary/ucdlib-theme-wp#102]
The space between icon panel header and content is too much. There have been a few times I want to use the icon header feature but opted not too because it looked strange with text so far apart, so fixing the space would make it more functional for more purposes.

Right now it looks like there is about 2rem space below the icon header:

![Screen Shot 2022-05-11 at 9 35 04 AM](https://user-images.githubusercontent.com/17831969/167902797-e43b509d-a89d-4dfa-9509-c6ef65dc85c8.png)

but I would prefer it only has 1rem:

![Screen Shot 2022-05-11 at 9 34 32 AM](https://user-images.githubusercontent.com/17831969/167902871-dcb61354-db90-4975-81bd-c02c8c2760e8.png)

**Comment by spelkey-ucd** [comment]
https://sandbox.library.ucdavis.edu/bug-fixes/#panel-margin

**Comment by wrenaria** [comment]
Looks good!
