### ISSUE TITLE
Panel with icon: background issue + can I show just the header?

### ISSUE THREAD

**Issue by wrenaria** [UCDavisLibrary/ucdlib-theme-wp#104]
EDIT: I moved my example from the stage [TOME Fund page](https://stage.library.ucdavis.edu/publish/open-access/tome-fund/) to sandbox so I can keep stage looking clean: 

https://sandbox.library.ucdavis.edu/panel-with-icon/

I am making a yellow box to highlight funded books. While I _can_ use just plain text (and I included a version below it styled that way), I think the icon on the header in the panel with icon with a nice touch. However, I can't hide the text body portion of the feature. In this use case, I really just want the header. Is that a feature we can support? 

Also, a white background is showing on the published view for some reason (looks fine in editor view).

![Screen Shot 2022-05-17 at 10 00 24 AM](https://user-images.githubusercontent.com/17831969/168869841-a79c1871-b019-4b66-a799-1d05e070c5ec.png)

**Comment by wrenaria** [comment]
The new Header with Icon block that came out of this should be limited to the same brand color palette as Panel with Icon. Currently all colors are available.

**Comment by spelkey-ucd** [comment]
Palette matches on stage now.

**Comment by wrenaria** [comment]
👍
