### ISSUE TITLE
Teaser needs to hide page author/date for linked pages

### ISSUE THREAD

**Issue by wrenaria** [UCDavisLibrary/ucdlib-theme-wp#105]
When I auto-populate a teaser by linking it to an existing page, it shows the author and page publication date with no way to remove it. This is undesirable behavior. I cannot think of a time where we would want to show the author and publish date of a normal webpage as part of a teaser. It makes sense for articles, but not standard pages.

Example:

![Screen Shot 2022-05-18 at 2 11 18 PM](https://user-images.githubusercontent.com/17831969/169156433-c1534c4a-4c34-4c75-aade-cdba116b607b.png)

**Comment by spelkey-ucd** [comment]
I you click the parent "teasers" (plural) block, there is an option to hide the byline:

<img width="502" alt="image" src="https://user-images.githubusercontent.com/34284106/169157148-351c827e-fe79-49a2-9e16-3145e5517687.png">

**Comment by wrenaria** [comment]
Oh. 😱  I would have not discovered that on my own lol. Thank you, I will close this issue.
