### ISSUE TITLE
Careers block

### ISSUE THREAD

**Issue by spelkey-ucd** [UCDavisLibrary/ucdlib-theme-wp#116]
We need two new blocks:
1. Career block with attributes for:
 - Title
 - Link
 - Salary (might need to be multiple attributes - min, max, unitText)
 - Final Filing date
2. Careers Block which will only accept a "career"(singular block) as an innerblock.
 - See `parent` attribute when registering block, and the [allowedBlocks property on useInnerBlocksProps](https://developer.wordpress.org/block-editor/how-to-guides/block-tutorial/nested-blocks-inner-blocks/#allowed-blocks)

Here is the design: https://xd.adobe.com/view/e29b8a3d-4a68-48e6-8e6a-7b32b41db74a-b7c8/ . 
<img width="649" alt="image" src="https://user-images.githubusercontent.com/34284106/171877098-32753b32-cdee-48b5-a6cc-a6589741540f.png">

When rendering, your careers block will do `<ul class='list--arrow'>{{content}}</ul>` and then your career blocks will be the `<li>`s.

A little extra step is to also render structured data as `json-ld`, so that search engines can find our jobs. You can follow the [instructions here.](https://developers.google.com/search/docs/advanced/structured-data/job-posting) The script tag doesn't need to live in the head, it can be side-by-side with the visible content. This only needs to happen on the public-facing page.

On the editor side, it might make sense to make a basic form that [displays in a modal](https://developer.wordpress.org/block-editor/reference-guides/components/modal/) when each career block is clicked.

**Comment by UcDust** [comment]
Hi @spelkey-ucd / @wrenaria 

Could we get some advice on the layout / verbiage for the career modal popup? Also in the screenshot you can see we used the _people_ icon from WP for the career block (and possibly also the careers block), if you'd like something more customized please let us know. This is what we have so far-

![career modal](https://user-images.githubusercontent.com/103536473/171917287-8aa1be5e-c964-42a2-8cfc-a34eb121d4b7.png)

**Comment by UcDust** [comment]
Actually I just noticed there's a [Datepicker component](https://github.com/WordPress/gutenberg/tree/6aef6e6b9b5cf2f5aeff6145cd24181edf0d43f0/packages/components/src/date-time) that could be used for the date instead of a normal input.

**Comment by spelkey-ucd** [comment]
nice. and you can use a regular url input instead of the fancier typeahead version since the link is always going to be external.

**Comment by UcDust** [comment]
Ok thanks. This is the latest version, with a normal url input and datepicker-

![Screen Shot 2022-06-03 at 11 22 53 AM](https://user-images.githubusercontent.com/103536473/171923709-467ad4f6-a643-42b4-988b-6c41cd6b9345.png)

**Comment by spelkey-ucd** [comment]
Have the salary frequency be a select with the following options:


  *   HOUR
  *   DAY
  *   WEEK
  *   MONTH
  *   YEAR
Which is what google uses

From: Dusty Cartwright ***@***.***>
Reply-To: UCDavisLibrary/ucdlib-theme-wp ***@***.***>
Date: Friday, June 3, 2022 at 2:23 PM
To: UCDavisLibrary/ucdlib-theme-wp ***@***.***>
Cc: Stephen A Pelkey ***@***.***>, Mention ***@***.***>
Subject: Re: [UCDavisLibrary/ucdlib-theme-wp] Careers block (Issue #116)


Ok thanks. This is the latest version, with a normal url input and datepicker-

[Image removed by sender. Screen Shot 2022-06-03 at 11 22 53 AM]<https://user-images.githubusercontent.com/103536473/171923709-467ad4f6-a643-42b4-988b-6c41cd6b9345.png>

**Comment by spelkey-ucd** [comment]
hmmm two things to consider there:
1. keep data entry at a minimum for HR
2. provide enough data to google to create a good entry

Based on what is displayed, looks like `employmentType` and `jobLocation` would be good things to add. And these are things you could prepopulate - most jobs are full time in Davis.

<img width="882" alt="image" src="https://user-images.githubusercontent.com/34284106/172253101-6061c7b9-f7f4-43fd-9fa9-d21a1b35a2c9.png">

here is what we currently have for the hiringOrganization:
```
          "hiringOrganization" => array(
              "@type" => "Organization",
              "name" => 'UC Davis Library',
              "sameAs" => "https://www.library.ucdavis.edu/",
              "logo" => "www.library.ucdavis.edu/wp-content/themes/ucd-lib/img/ucd-logo-main-new.png"
          ),
          "identifier" => array(
              "@type" => "PropertyValue",
              "name" => "UC Davis Library",
              "value" => $post->id
          ),
```
You can change the logo to `https://www.library.ucdavis.edu/wp-content/themes/ucdlib-theme-wp/assets/img/site-icon.png`

**Comment by sbagg** [comment]
But this is all for the uc davis library jobs right?  Does that mean job Location would always be library?

**Comment by spelkey-ucd** [comment]
two feature requests on the careers (plural) block i forgot to mention:
1) If there are no jobs listed, render some custom text (as a paragraph for now, kimmy might want something more elaborate, but shes on vacation). This text should be customizable, but default should be something like "there are no open positions at this time".
2) Add a toolbar option to lock the block, so that it cannot be removed by accident. This option should be on by default. To do this, you set the [lock attribute](https://make.wordpress.org/core/2022/01/08/locking-blocks-in-wordpress-5-9/) an an object: `{remove: true, move: true)`

**Comment by spelkey-ucd** [comment]
Currently, running into an issue where it's hard to select the careers block if it doesn't have any careers:
<img width="548" alt="image" src="https://user-images.githubusercontent.com/34284106/173864546-5e6dfb41-353e-4a33-baa7-c57b77a6ff46.png">

Can you add an "add career" button if there are no careers listed? To detect if you have a career, it would go something like this:
```js
        const { clientId, setAttributes, attributes } = props;
        const { innerBlocksCount} = useSelect(select => ({
            innerBlocksCount: select("core/block-editor").getBlockCount(clientId)
        }));
```

**Comment by UcDust** [comment]
For sure, I'll take a look.

**Comment by UcDust** [comment]
Would something like this work by chance, basically if they click to remove block, it just clears the values from the block but leaves a single empty block in the careers block?-

![Screen Shot 2022-06-15 at 1 13 33 PM](https://user-images.githubusercontent.com/103536473/173918607-d89c4dd7-cb7e-4795-beb8-8dc12acc7153.png)

**Comment by UcDust** [comment]
@spelkey-ucd I just committed the latest code, it seems to work pretty well but please let me know if you want anything changed. Thanks!

**Comment by spelkey-ucd** [comment]
put in another pull request and ill get it merged

**Comment by UcDust** [comment]
Hi @wrenaria, this should be in sandbox now. Please let us know if you spot anything, thanks!

**Comment by wrenaria** [comment]
The Careers block is forever. I cannot delete the block. 

For example, there's two separate Careers blocks on this page, one filled out, one empty: https://sandbox.library.ucdavis.edu/careers-and-internships/  

I cannot delete the spare from either the menu or by using the Delete button on my keyboard. 

![Screen Shot 2022-06-21 at 11 11 22 AM](https://user-images.githubusercontent.com/17831969/174869641-161de8c3-1ba6-4d09-ae9f-90023eb9019b.png)

This results in the following display on my published page:

![Screen Shot 2022-06-21 at 11 15 43 AM](https://user-images.githubusercontent.com/17831969/174870052-50da45d6-d2cb-474d-bf85-5e9289fb2afa.png)

**Comment by spelkey-ucd** [comment]
mwahahahahahahahahaaaaaaaa 

click the lock icon in the block toolbar

<img width="530" alt="image" src="https://user-images.githubusercontent.com/34284106/174870594-924af084-f305-42ec-89b9-8f8116e4aea6.png">

it is locked by default to prevent  hr from accidentally deleting their jobs.

we could change the default to be not locked?

**Comment by UcDust** [comment]
@wrenaria I think that's because we set the careers block to be locked by default, so it would prevent deletion. I unlocked it and it seemed to let me delete that spare one on the bottom-

![Screen Shot 2022-06-21 at 11 19 08 AM](https://user-images.githubusercontent.com/103536473/174870618-b17a2be2-c0b8-4a31-a792-8b9c098efb52.png)

Do you think we should add some padding to the top of the careers block in the editor so that's it's easier to select it? Selecting on the left side of the list also selects it, but perhaps this will cause some confusion?

**Comment by wrenaria** [comment]
Oh, can we also add more space between the positions? It's easier to read / looks better when I put them in separate blocks: 

![Screen Shot 2022-06-21 at 12 48 12 PM](https://user-images.githubusercontent.com/17831969/174885472-0c7f7d8e-0d4e-4a1b-9a94-792e4f331518.png)

I want this same spacing between positions listed within the same block / without having to make a separate block for each position.

**Comment by wrenaria** [comment]
This looks good but I am left with one question:

Why do we have a field for Employment Type if that info isn't displayed ?

**Comment by UcDust** [comment]
Good call, I meant to add that into the ui, one sec

**Comment by wrenaria** [comment]
Oh I see! Err, let's leave it as is, I guess?
