### ISSUE TITLE
Float option for background-color block

### ISSUE THREAD

**Issue by spelkey-ucd** [UCDavisLibrary/ucdlib-theme-wp#118]
Kimmy would like the background-color block to have the option to float it right or left.

This functionality is already implemented in the brand-textbox block, so you can look there for the pattern. Basically, you just need to apply the `u-align--right` or `u-align--left` class and set the max-width to 33%. 

The editor-side display doesn't need to actually float - it can stay as a 100% width block.

**Comment by spelkey-ucd** [comment]
yep

**Comment by wrenaria** [comment]
Looks good to me!

**Comment by wrenaria** [comment]
I've discovered a problem! This is what float looks like on mobile:

<img src="https://user-images.githubusercontent.com/17831969/174918415-7a7de2ca-cede-42f4-b25d-ddea84956a93.PNG" width="300">

This is not ideal. The float feature probably ought to either [1] take up 50% of the space at mobile sizes (<768ish px) with text continuing to wrap [or 2] stop floating left/right and become full width again on small device/mobile views.

I think maybe I'm inclined toward 1 but am okay with either solution.

**Comment by UcDust** [comment]
Good call! We can go with option 1.
