### ISSUE TITLE
Social Media Block

### ISSUE THREAD

**Issue by spelkey-ucd** [UCDavisLibrary/ucdlib-theme-wp#122]
http://dev.webstyleguide.ucdavis.edu/redesign/?p=molecules-social-follow

**Comment by UcDust** [comment]
Hi @wrenaria,
Would it be possible to get an svg icon for each of the individual social icons by chance?

**Comment by UcDust** [comment]
Hi @spelkey-ucd,
Are these links supposed to just point back to UCD social networks, or should they be customizable with link text? If the latter, and not all links are filled out, should we hide the icons if unfilled?

**Comment by wrenaria** [comment]
@UcDust 

Can you use the Font Awesome icons? All the social icons you need are there. I don't know what the campus PatternLab is using for the background on the Instragram circle, is it possible you can pull that stuff from them / the link Steve shared?

These icons will be linking to the UC Davis Library social media accounts. You can find our social links in the footer of our current [production site](https://www.library.ucdavis.edu/). Any links not in use should be hidden.

Ultimately, these links will end up looking like this in our footer: https://xd.adobe.com/view/64736c3e-1904-41d0-b5f0-c76326e27854-3120/

**Comment by spelkey-ucd** [comment]
url hrefs should be attributes on the block. like kimmy said, hide if not used.

yeah, front end uses a sprite sheet for the icon bubbles - http://dev.webstyleguide.ucdavis.edu/redesign/images/social-follow.svg.  lets stay on brand and use this (but hosted on our site). if more social media sites need to be added, we will cross that bridge when we come to it.

if you need icons in the toolbar or inspector controls on the editor side, you can use font awesome with the `ucdlib-icon` element:
`<ucdlib-icon icon='ucd-public:fa-twitter'></ucdlib-icon>`

**Comment by UcDust** [comment]
Ok thanks! I noticed there's a core 'Social Icons' already, should we try to hide this as well?

![Screen Shot 2022-06-10 at 9 21 40 AM](https://user-images.githubusercontent.com/103536473/173109314-f34294e8-72c1-4944-a3cc-7336e8add697.png)

**Comment by UcDust** [comment]
Also, would something like a single 'links' tool icon and modal suffice to populate the links?-

![Screen Shot 2022-06-10 at 1 06 39 PM](https://user-images.githubusercontent.com/103536473/173142705-51172107-d4ad-4592-a395-f56577ce09be.png)

**Comment by spelkey-ucd** [comment]
yeah, hide the core and force people to use the brand block. 

A modal with inputs is fine with me, but make sure you have a placeholder in the block area, so that users can more easily find the block if it doesnt have any links.

**Comment by UcDust** [comment]
@spelkey-ucd I've created a pull request for this, please let us know if you'd like anything changed.

**Comment by UcDust** [comment]
Hi @wrenaria, it looks like this should be in sandbox now.

**Comment by spelkey-ucd** [comment]
not yet! still have to deploy.

auto deployments are hooked up to pull requests on the [daddy repo](https://github.com/UCDavisLibrary/main-wp-website), but not the submodules

**Comment by UcDust** [comment]
Oops sorry!

**Comment by wrenaria** [comment]
@UcDust The social buttons are positioned a little too close together, can you add 0.5rem of space between each one?

**Comment by UcDust** [comment]
@wrenaria 

For sure, does this look better?-

![Screen Shot 2022-07-18 at 7 59 12 AM](https://user-images.githubusercontent.com/103536473/179540678-7bd76ce5-d363-4fda-aadd-f939fa9b322e.png)

**Comment by wrenaria** [comment]
@UcDust Perfect, thanks!
