### ISSUE TITLE
slideshow block

### ISSUE THREAD

**Issue by spelkey-ucd** [UCDavisLibrary/ucdlib-theme-wp#135]
http://dev.webstyleguide.ucdavis.edu/redesign/?p=molecules-slideshow-thumbnails

https://github.com/ucd-library/ucdlib-theme-sass/blob/main/source/js/slideshow.js

Just going to build it using wordpres jquery.

**Comment by spelkey-ucd** [comment]
https://sandbox.library.ucdavis.edu/slideshoooows/

**Comment by wrenaria** [comment]
@spelkey-ucd This looks great until you put images of varying aspect ratios into it! Which is something ASC will definitely want/need to do. 

I'd like the slideshow to have a fixed aspect for the image areas of the slideshow (16:9? or 4:3?) and have the image contained in the available space (or if possible include an option to toggle between **contain** and **cover** fit options to suit the needs of the context). 

I think `#333333` should work fine for the background color to fill the dead space around narrower images. 

Here's an example slideshow with fixed aspect + contained image to help you see what I am after: https://scalar.usc.edu/works/from-vine-to-wine/tasting-the-good-life?path=exhibition-categories

**Comment by spelkey-ucd** [comment]
@wrenaria slideshow now has an option to set the aspect ratio:
<img width="787" alt="image" src="https://user-images.githubusercontent.com/34284106/177585435-5ed5c170-553c-428b-9e38-db0764aa8a2e.png">

I left `inherit from photo` as an option in case an advanced user (aka you) needs to break the mold and use a custom aspect ratio. I can remove it if you think it is unnecessary.

If an aspect ratio is selected, the user can toggle between `cover` and `contain` fit: 
<img width="865" alt="image" src="https://user-images.githubusercontent.com/34284106/177585571-439e13c5-ae5b-40b1-a117-112c48e02bda.png">


https://sandbox.library.ucdavis.edu/slideshoooows/#contain

**Comment by wrenaria** [comment]
@spelkey-ucd Nice improvements!

One more change to make: I'm fine with thumbnails keeping their individual aspects, but I want them all to appear at the same max height no matter the displayed aspect so it's not a crazy jagged variable shape at the bottom.

**Comment by spelkey-ucd** [comment]
thumbnails now display the same as the main image (just smaller). on stage/sandbox.
