### ISSUE TITLE
Add Share Buttons to News Articles

### ISSUE THREAD

**Issue by wrenaria** [UCDavisLibrary/ucdlib-theme-wp#160]
Share buttons need to be added to News posts. Share buttons appear below the author and above the Quick Summary. Here is an example from [PatternLab article page](http://dev.webstyleguide.ucdavis.edu/redesign/?p=pages-article):

![Screen Shot 2022-07-12 at 9 38 41 AM](https://user-images.githubusercontent.com/17831969/178547336-87702a60-d77b-485f-919b-9ba935378d4d.png)

I seem to recall you wanted to potentially use a different solution than what SiteFarm does? It's a dim memory. However you want to make it happen, Share buttons should be added to Articles.

**Comment by spelkey-ucd** [comment]
this is on stage. let me know if you would like a different set of social media sites to display.

**Comment by wrenaria** [comment]
The email button throws a "no longer available" error. Looks like they stopped supporting that option or something? Since it's not working properly, let's hide that option.

Let's just show: `Facebook` `Twitter` `LinkedIn`

**Comment by spelkey-ucd** [comment]
updated

**Comment by wrenaria** [comment]
👍
