### ISSUE TITLE
Fancy header gold dots do not display correctly next to aligned images

### ISSUE THREAD

**Issue by wrenaria** [UCDavisLibrary/ucdlib-theme-wp#179]
Fancy header gold dots do not display correctly when next to aligned images.

![Screen Shot 2022-07-18 at 10 16 50 AM](https://user-images.githubusercontent.com/17831969/179566805-676ffe6a-f8cb-4efe-b7c4-1c465dcadaee.png)

Where'd my dots go? ☹️  _(A: behind the image)_

I set up an example on sandbox for testing: https://sandbox.library.ucdavis.edu/wp-admin/post.php?post=9172&action=edit 

![Screen Shot 2022-07-18 at 10 24 15 AM](https://user-images.githubusercontent.com/17831969/179567993-9040b06a-b7a5-4f5e-a3ab-6f0441090842.png)

**Comment by spelkey-ucd** [comment]
fix is on sandbox and stage

**Comment by wrenaria** [comment]
Looks good!
