### ISSUE TITLE
Teasers: Cannot delete description text

### ISSUE THREAD

**Issue by wrenaria** [UCDavisLibrary/ucdlib-theme-wp#183]
There is a bug where you cannot delete **Teaser** text. If you delete all the text and save, it reverts to whatever was there before deletion. There seems to be a min requirement of 1 character. The only way to revert to a descriptionless teaser is to put in a new one and delete the old. Please fix!

**Comment by spelkey-ucd** [comment]
this is fixed for teasers in which the linked post does not have a title/excerpt. 

in the case of linked posts, if the title or excerpt field is empty, that's how the teaser knows to fallback and display the post title/excerpt, so the custom fields can't be empty.
