### ISSUE TITLE
Scrollbar appearing on lists

### ISSUE THREAD

**Issue by wrenaria** [UCDavisLibrary/ucdlib-theme-wp#184]
Scrollbars are appearing on lists styled with "border between items":

![Screen Shot 2022-07-25 at 9 51 25 AM](https://user-images.githubusercontent.com/17831969/180833621-79fdc500-7bc9-4a8d-85d9-dd9d974b9fe9.png)
Example above is from [Author Rights and Copyright](https://stage.library.ucdavis.edu/author-copyright/) on Stage.

Other lists appear to be fine. There is a tester page of lists on Sandbox available at https://sandbox.library.ucdavis.edu/lists/

**Comment by spelkey-ucd** [comment]
fix is on stage
