### ISSUE TITLE
Exhibits Adjustments

### ISSUE THREAD

**Issue by wrenaria** [UCDavisLibrary/ucdlib-theme-wp#187]
# 1: Location/Date Header Spacing
Too much space between them. I dropped the 0.7 margin to 0.25 and it looks pretty good.
| Current: 0.75 | Preferred: 0.25 |
| --- | --- |
| ![Screen Shot 2022-07-27 at 12 17 20 PM](https://user-images.githubusercontent.com/17831969/181354328-8a78156a-ad82-4ade-ab3f-af045977730a.png) | ![Screen Shot 2022-07-27 at 12 17 42 PM](https://user-images.githubusercontent.com/17831969/181354363-71990cb0-aa70-433e-ae35-8e5828de9d6c.png) |

# 2: Department name displayed too small on exhibit credit
Currently displayed at **h6** size, but it should be **h5 / 1.207rem**

| Current | Preferred |
| -- | -- |
| ![Screen Shot 2022-07-27 at 12 40 28 PM](https://user-images.githubusercontent.com/17831969/181358173-0424ec9c-1e02-42cf-8c52-d4891e0e0392.png) | ![Screen Shot 2022-07-27 at 12 40 16 PM](https://user-images.githubusercontent.com/17831969/181358213-581b9195-2be1-4779-a5d1-70a29bbbeeb8.png) |

# 3: Next/Previous Button Layout
My original design was pretty basic, but I'd rather do something similar to what is on [Strategic Plan](https://stage.library.ucdavis.edu/leadership-mission-and-strategy/strategic-plan/priority-1/) pages to provide a clearer visual separation between content and page navigation. 

Keep the solid yellow + chevrons you have in lieu of the "prev" "next" text on my linked example though (I just am unable to replicate that using regular buttons on other pages so text is my best option on the Strategy pages).

![image](https://user-images.githubusercontent.com/17831969/181355596-df45cc75-6ffc-4600-a857-eb5ad902aa5e.png)

# 4: Title size on Exhibits Highlights/Hero Banner is too big
Title text is too big. So big it's kind of hard to read. Any idea why em and not rem? 

Playing in inspector, **1 em** looks better on desktop sizes, but then is really small on mobile sizes. **2.5 rem** looks alright at all sizes. 

I like the text size of location and date on Exhibit Highlights. Can we change Hero Banners to have the same text rules as Exhibit Previews? Right now, Hero Banners are only used for Exhibits landing page, so it would be nice for them to match stylistically.

# 5: Hide deeper level subpages from Exhibit Subnav
Sometimes I need a deeper level child in a multipage exhibit but I don't want it to display in the Exhibit subnav. For example, on the [Centennial exhibit](https://stage.library.ucdavis.edu/exhibit/uc-davis-centennial/timeline/), I need to link to a page with more info about something, like this [CK Ogden Library page](https://stage.library.ucdavis.edu/exhibit/uc-davis-centennial/timeline/1958-ogden-library/):

![Screen Shot 2022-07-27 at 12 45 20 PM](https://user-images.githubusercontent.com/17831969/181358842-c9b5d7cb-ae23-4181-a725-082604dd5df2.png)
--

I want it to be a exhibit subpage so that it displays the exhibit's primary subnav on the page and isn't considered a lone exhibit, but I don't want it to show up as a child page in the subnav:

![Screen Shot 2022-07-27 at 12 47 47 PM](https://user-images.githubusercontent.com/17831969/181359373-e7f846e3-52e7-4ef3-ad06-92e43ba73533.png)

The easiest solution to this is probably to disable display of child pages altogether, which is something I am fine with doing for exhibits. They should favor simple navigation generally anyway.

**Comment by spelkey-ucd** [comment]
these changes are all on stage

**Comment by wrenaria** [comment]
This looks good except that the hero banners the title and description text are appearing close to the same size on desktop and too disparate on small screens (description is teeny on a phone -- em vs rem issue, I assume). 

For hero banners can we have description text at `1.6rem text` with `1.2 line height` and `0.5 top margin`, that would be better for this context. 

## Examples

### Desktop (left is current, right is preferred)

![Screen Shot 2022-08-03 at 8 58 11 AM](https://user-images.githubusercontent.com/17831969/182654942-e65c0580-744b-45e8-a047-e4170366c5d2.png)
---
### Mobile (left current, right preferred)

![Screen Shot 2022-08-03 at 9 03 58 AM](https://user-images.githubusercontent.com/17831969/182656024-baa2e615-1f9f-4a11-9c4f-1ccc53b4bb78.png)

**Comment by wrenaria** [comment]
As follow-up to our zoom chat --- here are ~~two~~ three (sorry, I see another) other issues to resolve in addition to the one above:

## Issue: Location Info on Exhibits
For online exhibits that had a past physical component in the past, don't display the physical information at the top. The little blurb in the sidebar covers the past physical display info. Mixed online and physical exhibits should only show the date in the main body area until the end date has past, then shift the info to the exhibit credit box. 

### Rulezzz:
**Show location/date info on:**
- Physical exhibits actively on display in the library (with or without an online component)
- Past physical exhibits with no online component

**Do not show location/date info on:**
- Online only exhibits
- Mixed online/physical exhibits where the physical date is in the past/expired (this info is displayed in the exhibit credit box instead, as shown below)

![Screen Shot 2022-08-03 at 10 18 07 AM](https://user-images.githubusercontent.com/17831969/182678096-f2f564da-ffeb-43d7-baf9-6c1c4019121e.png)

## Issue: Brand color options for Exhibits
In order to maintain text accessibility, the brand colors available for Exhibits should be the same as the ones used in `Exhibit Highlights` and `Hero Banner` blocks. 

I also do not want the color in the title bar to change on Exhibits when you set a brand color since the darker palette does not reflect the rest of the site's go-to accent colors.

## Issue: Exhibit location map?
Originally we planned to show a location map in the sidebar of only **active/not expired physical exhibits**. Does that feature exist and if so where/how do I update the image/text content for it?

Example in this XD file: https://xd.adobe.com/view/b654c7fd-95bc-44b8-b13a-e1aa72567e96-e307/screen/36054c61-220d-4f9b-8b1b-6cc130a5d972/ 

This item isn't super critical if it doesn't exist and there's no time to add it; it can get added to the post-launch enhancements list.

**Comment by wrenaria** [comment]
The **Excerpt** field is missing from Exhibit page settings. Since excerpts show on Online Exhibits page, I need access to be able to customize them.

**Comment by spelkey-ucd** [comment]
These changes are on stage.

The location map can be uploaded in the exhibit metadata section:
![image](https://user-images.githubusercontent.com/34284106/183509290-f796aadb-54fc-4169-ad7f-79e0cb3531ee.png)

I have uploaded an example to the dog exhibit: https://stage.library.ucdavis.edu/exhibit/fleetfield-gallery-dog-art-display/

**Comment by wrenaria** [comment]
Sorry, slow to get to this because of being low on my priority list for content deadlines. Plenty of time to look now that we're in tech/content freeze, ha, so here's some post-launch adjustments to make.  

In regards to **Exhibit Location Map** update:

If it's tied to exhibit metadata, doesn't that mean you have to associate an exhibit map every time there's a new exhibit? But exhibit locations are a fixed list, so the locations are consistent (and thus so are their maps). I expected that I'd upload a map for each fixed exhibit location and a content creator wouldn't need to do anything on their end beside pick a location from the list like usual.

# Other Things
## One More Location/Date Header Spacing Adjustment
The closer together date/location looks great, but seems like we also lost space between it and body content. There needs to be more separation there.

![Screen Shot 2022-08-15 at 10 06 10 AM](https://user-images.githubusercontent.com/17831969/184682014-4cdd3995-ede4-48e6-9617-9bbb9533a452.png)

##  Location Info on Exhibit Highlights

These need to follow similar rules as exhibits do. I don't want to see dates on [online exhibits](https://stage.library.ucdavis.edu/exhibits/online-exhibits/) that have a **past** physical exhibit, they should just say "online exhibit" like Picnic Day does below otherwise we get this weird mix in the featured area of the online exhibits page with potentially really old dates. 

![Screen Shot 2022-08-15 at 10 13 38 AM](https://user-images.githubusercontent.com/17831969/184684281-9b9a2ba0-4ac6-426d-9027-5a24e9e47ae0.png)

**Comment by spelkey-ucd** [comment]
where should the curation notes display? In this widget, below the `curated by`?
![image](https://user-images.githubusercontent.com/34284106/186006650-e54bc55d-a706-490d-9b1b-f2c0d7aaf4b2.png)
And how should they be styled?

**Comment by spelkey-ucd** [comment]
@wrenaria 

# location map

Sorry, I was under the impression that these were on an exhibit-level. I added an image upload and text field to each exhibit location taxonomy term for a map and directions:

![image](https://user-images.githubusercontent.com/34284106/186432886-13aed4b0-719b-43f5-9742-17228f7ccf79.png)


and in action: https://sandbox.library.ucdavis.edu/exhibit/democracy-by-participation-the-life-and-legacy-of-cruz-reynoso/

# One More Location/Date Header Spacing Adjustment

1.5rem spacing applied: https://sandbox.library.ucdavis.edu/exhibit/democracy-by-participation-the-life-and-legacy-of-cruz-reynoso/

# Location Info on Exhibit Highlights

Dates/location are only displayed for current exhibits:
https://sandbox.library.ucdavis.edu/exhibits/online-exhibits/
https://sandbox.library.ucdavis.edu/exhibits/exhibits-in-the-library/

# Need a free text option for curators

See my question above. Sorry, forgot to ping you in the comment.

# Add a URL option to Curator Organization info
There is now a link field on each curator organization taxonomy term:
![image](https://user-images.githubusercontent.com/34284106/186436308-b3be9e7e-8858-418f-b5b7-00fe2f97f0f7.png)

**Comment by spelkey-ucd** [comment]
- Is there a way to do this without having to build a profile every time we have a guest curator or news author?
  No, that is the correct way of doing it. 

  Although, one clarifying point. At present, news uses the default wordpress authorship field, which links user accounts not person profiles. We can change this to be more like exhibits, but somebody else will have to code it or it will have to wait until im back from leave.

    Can past employees automatically cease to be linked in the exhibits credit when their profile is marked as "No Longer Employed at Library"?
- Can do

**Comment by spelkey-ucd** [comment]
Past employee removal is own issue: #219
