### ISSUE TITLE
Add "caption" text css class for use in advanced 

### ISSUE THREAD

**Issue by wrenaria** [UCDavisLibrary/ucdlib-theme-wp#188]
Adding this issue to capture our conversation about this earlier -- Please add a css style called "caption" that can be used to style paragraph text to look like photo captions via the "Additional CSS class(es)" field.

**Comment by spelkey-ucd** [comment]
this is on stage

**Comment by wrenaria** [comment]
I know it's a small thing, but this is awesome, thank you!
