### ISSUE TITLE
Add columns option to Person Query block

### ISSUE THREAD

**Issue by wrenaria** [UCDavisLibrary/ucdlib-theme-wp#189]
Add a 2 column layout option to the Person Query block. 

Single column can be the default, but a 2 column option will help with making nicer layouts for larger teams on department pages.

**Comment by spelkey-ucd** [comment]
@wrenaria How should sort work?

A B
C D
E F

or 

A D
B E
C F

**Comment by wrenaria** [comment]
Let's go with:

A B
C D
E F

**Comment by spelkey-ucd** [comment]
@wrenaria this feature is on stage:

https://stage.library.ucdavis.edu/online-strategy/#staff 

There is now a block setting for `Number of Columns`

![image](https://user-images.githubusercontent.com/34284106/213786033-257d5f0b-3f5d-45c5-92a6-0700a4d4ec9e.png)
