### ISSUE TITLE
Library Services -- drop 2 rem spacing down to 1 rem

### ISSUE THREAD

**Issue by wrenaria** [UCDavisLibrary/ucdlib-theme-wp#190]
There is currently too much space between the service entries in the Services Directory. 

Image below: Left is current spacing (2 rem), right is preferred (1 rem).

![Screen Shot 2022-07-25 at 2 57 09 PM](https://user-images.githubusercontent.com/17831969/181362999-6a631a90-7f16-4545-931b-ef695cc94234.png)

**Comment by spelkey-ucd** [comment]
this is on stage
