### ISSUE TITLE
News: UI should display captions on feature images

### ISSUE THREAD

**Issue by wrenaria** [UCDavisLibrary/ucdlib-theme-wp#194]
This is a low priority enhancement that can wait until post go-live. 

Our current **production site** News supports captions on feature images:

- https://www.library.ucdavis.edu/news/new-lecture-series-on-food-and-wine-kicks-off-with-a-focus-on-food-waste/ 
- https://www.library.ucdavis.edu/news/honoring-juneteenth/

And **SiteFarm** News supports captions displaying on feature images:

- https://biology.ucdavis.edu/news/national-academy-inventors-inducts-walter-leal
- https://caes.ucdavis.edu/news/4-million-endowment-bolsters-uc-davis-viticulture-and-enology 

But our **Stage** News on does not:

- https://stage.library.ucdavis.edu/news/new-lecture-series-on-food-and-wine-kicks-off-with-a-focus-on-food-waste/ 
- https://stage.library.ucdavis.edu/news/honoring-juneteenth/

**Comment by NeilWeingarten** [comment]
I've added this as a post-live issue.  Let me know if it gets resolved before go-live and I'll remove it from that list.

**Comment by spelkey-ucd** [comment]
captions are showing on stage for me...

looks like this was a data issue?  and not a templating issue?
