### ISSUE TITLE
Directory Filter Adjustments

### ISSUE THREAD

**Issue by wrenaria** [UCDavisLibrary/ucdlib-theme-wp#195]
This is a high priority issue to complete prior to launch. We need to make a few changes to filters to make behavior better align with user expectations when filtering the directory.

**1:** Remove keywords from the "Name or Keyword" freeform search. We will just search `Name`.

**2:** Add the rest of the directory tags to the Subject Area filter. This involves a few changes:
- Rename `Subject Area` to `Expertise`
- Use option groups to split directory tags into two groups. 
-- The current `Subject Area` tags should be listed **first** under the group heading `Academic Subjects`
-- The rest of the tags will fall into a group called `Other Expertise`
-- The hint text should read `Select Expertise`

![Screen Shot 2022-07-29 at 11 54 52 AM](https://user-images.githubusercontent.com/17831969/181826204-dbd07686-d7bb-4198-9fdc-4cefe6843a61.png)

Since we are losing the ability to search the "areas of expertise" free-form text, I would like to circle back and talk about splitting search out from filters for a more robust directory experience post-launch, but this will work well enough for now.

**Comment by spelkey-ucd** [comment]
these changes are on stage

**Comment by wrenaria** [comment]
Much more user friendly, thank you!
