### ISSUE TITLE
Percent width container for image placement is broken

### ISSUE THREAD

**Issue by wrenaria** [UCDavisLibrary/ucdlib-theme-wp#211]
It wasn't working at all for a bit, now it is leaving a bunch of extra space to the right of right-aligned images as you can see in the examples below.

### Example 1:
![Screen Shot 2022-08-13 at 9 18 33 AM](https://user-images.githubusercontent.com/17831969/184502583-afb06f57-6999-44c9-b544-8179f20db15f.png)
**Source:** https://stage.library.ucdavis.edu/archives-and-special-collections/visitor-information/class-visits/ 

### Example 2:
![Screen Shot 2022-08-13 at 9 26 39 AM](https://user-images.githubusercontent.com/17831969/184502642-257bbe42-56f6-4953-a6b3-925f13889394.png)
**Source:** https://stage.library.ucdavis.edu/location/peter-j-shields-library/

**Comment by wrenaria** [comment]
This looks good!

**Comment by wrenaria** [comment]
Oh wait! I forgot to check it on my phone. Did it always do this? 

<img src="https://user-images.githubusercontent.com/17831969/185968727-db82dc7f-7382-4e43-ad8c-83c3942f4f24.jpg" width="320">

If the image is going to break to its own line in mobile, I'd rather drop the size percentage entirely at that point and let it fill the space since text isn't wrapping around it anymore and phone screens are small so larger images are more helpful in that context.

**Comment by spelkey-ucd** [comment]
I can set it to 100% on mobile, or I can stop it from breaking to its own line. Preference?

**Comment by wrenaria** [comment]
I like the second option --  less than 50% continue wrapping, otherwise drop to new and make 100%

**Comment by spelkey-ucd** [comment]
deployed to website_tag: v3.1.0
