### ISSUE TITLE
Increase # of trumba events displayed

### ISSUE THREAD

**Issue by wrenaria** [UCDavisLibrary/ucdlib-theme-wp#213]
Is it possible to control the number of Trumba events displayed? Can we up it to five? Three looks okay in the sidebar of pages, but it looks kind of small and sad on homepage since the small text size / no images layout makes it so much smaller than surrounding columns. A couple more events showing should help with that a wee bit.

If there's an option to choose # of event to display, that would be even better (or a 3 and 5 version?), but I don't know Trumba's limitations.

**Comment by spelkey-ucd** [comment]
@wrenaria being able to easily control the number of events displayed would be a reasonable expectation, but it looks like Trumba makes it difficult.

[It's not something I can do programmatically](https://www.trumba.com/help/api/addSpud_method.aspx). 

Based on [this documentation](https://www.trumba.com/help/publish/puboverview.aspx), I can customize widgets by using the `publish settings`, but our account does not seem to have this option:
![image](https://user-images.githubusercontent.com/34284106/185685703-04715eb7-b652-4cb7-b235-386793519cbe.png)

So if we want a new 5 event widget, we will have to ask someone with publishing rights, and I have no idea who that is. Maybe Jessica knows?

**Comment by spelkey-ucd** [comment]
@wrenaria sorry, I spoke too soon. Ignore everything I said above.

There are some [advanced options](https://www.trumba.com/help/api/urlparameters.aspx) i missed.

Yes, we can control the number of events.

**Comment by spelkey-ucd** [comment]
@wrenaria 5 occurrences of "Morning Tea Mindfulness Meditation" are now on sandbox:
https://sandbox.library.ucdavis.edu/

**Comment by wrenaria** [comment]
So much tea 😂 This is fine, there will hopefully be other events added/going on during the academic year to break up the wall of tea.

**Comment by spelkey-ucd** [comment]
deployed to website_tag: v3.1.0
