### ISSUE TITLE
Styles adjustments for Gallery captions

### ISSUE THREAD

**Issue by wrenaria** [UCDavisLibrary/ucdlib-theme-wp#215]
The captions on WP gallery images are very hard and sometimes impossible to read in their current state. I don't think they need huge adjustments to fix this, here is what I am thinking:

- solid background instead of gradient,
- 50% opacity
- text size `0.875rem` to match the size of regular captions.
- appx `8px` padding around the text

Current | Approximate Goals
--- | ---
![Screen Shot 2022-08-17 at 2 58 07 PM](https://user-images.githubusercontent.com/17831969/185250868-235b5a5a-2c5e-4bea-b8c3-bbd52e4b5950.png) | ![Screen Shot 2022-08-17 at 2 58 21 PM](https://user-images.githubusercontent.com/17831969/185250898-fda5310f-3058-446b-b9db-01a8db4625dc.png)

_Example from https://library.ucdavis.edu/exhibit/ground-beneath-our-feet-nikola-p-prokopovich-papers-on-land-subsidence/_ 

Still hoping for lightbox feature at some point too to improve image viewing (but the caption styling change above is more pressing in the short term for site readability).

**Comment by wrenaria** [comment]
Looks good to me!

**Comment by spelkey-ucd** [comment]
deployed to website_tag: v3.1.0
