### ISSUE TITLE
ASC/Map Room Hours Display on Main Hours Page

### ISSUE THREAD

**Issue by wrenaria** [UCDavisLibrary/ucdlib-theme-wp#220]
## The Original Request
ASC (via Jenny) sent these requests for adjustments to the [main hours display](https://library.ucdavis.edu/hours/) on the library website:

1. Map collection currently reads as closed. There should be "Make an appointment" or "Schedule a Visit" links for Tuesday and Wednesday.

2. Update the "Schedule a Visit" language on the ASC hours to match what's on [the department page](https://library.ucdavis.edu/archives-and-special-collections/): "Make a Morning Appointment"

## Recommended Solution / Mockup
Currently thinking it might be best/probably simplest to hide the special daily display of appointment link and hide Map Collection hours altogether, replacing them with a basic text sentence and link that is generic enough to cover any specific day or hours availability changes they may make. I will need to check with Jenny to see how long they plan to keep Map Room open by appointment only. 

![Screen Shot 2022-08-29 at 4 25 20 PM](https://user-images.githubusercontent.com/17831969/187316077-514120f7-0cc3-48b9-a5cc-53df9beba747.png)

## Text and Links to Use

**Archives and Special Collections:**
`For morning visits, please schedule an appointment. Walk-ins are welcome during our open hours. `

Link: https://reservations.library.ucdavis.edu/reserve/asc/archivesandspecialcollections 

**Map Collection:**
`To visit the Map Room, please schedule an appointment.`

Link: https://reservations.library.ucdavis.edu/reserve/asc/maproom

**Comment by spelkey-ucd** [comment]
@sbagg looks like this has been implemented in production? can i close?

**Comment by sbagg** [comment]
Yes I will close it
