### ISSUE TITLE
Careers block additions: description, related materials, autohide after end date

### ISSUE THREAD

**Issue by wrenaria** [UCDavisLibrary/ucdlib-theme-wp#221]
Some additions have been requested to be added to the Careers block to better support providing more information for special positions such as leadership roles. 

Requested changes include:

- Add an optional description field that supports links
- Add an optional link list for "related materials" where link count varies depending on need
- Auto-hide career positions from the user-facing view once the end date has passed

XD mock-up of Careers page reflecting these changes:
https://xd.adobe.com/view/cf0ef48c-c62f-4e9d-beb9-777ad98f282f-9a5d/?hints=off 

Mock-up of just the Careers block:
<img width="797" alt="Screen Shot 2022-09-09 at 11 40 14 AM" src="https://user-images.githubusercontent.com/17831969/189421293-36772f30-4426-4e2f-a892-16fec5daf20b.png">

**Comment by wrenaria** [comment]
Oh, a couple additional requests of my own I forgot to include, if you don't mind:

- Can we hide the cents on figures that don't include them? For example, 66,000 instead of 66,000.00 ? It's easier to read that way.
- Currently dates show a 0 in front of single digit day, but this is not a usual way to display day in the written out date format we are displaying. Can we remove the zero?

Field | Current | Preferred
--- | --- | ---
Salary | ![Screen Shot 2022-09-09 at 11 51 28 AM](https://user-images.githubusercontent.com/17831969/189423276-4fb985eb-89d8-4fd4-a481-ac6e0be3cf8b.png) | ![Screen Shot 2022-09-09 at 11 52 34 AM](https://user-images.githubusercontent.com/17831969/189423400-9e042e18-fcb6-4e6d-85f6-04d8baabcc95.png)
Date | ![Screen Shot 2022-09-09 at 11 47 56 AM](https://user-images.githubusercontent.com/17831969/189423048-fad4a592-f1fb-4076-81ba-4acaaa2fa042.png) | ![Screen Shot 2022-09-09 at 11 50 50 AM](https://user-images.githubusercontent.com/17831969/189423090-7957bbb2-0e3a-4a8a-aa5f-07d0e3e1f549.png)

**Comment by UcDust** [comment]
@wrenaria will do!

**Comment by UcDust** [comment]
@wrenaria 

This is live on sandbox now, I also made a sample page if it's helpful-

https://sandbox.library.ucdavis.edu/wp-admin/post.php?post=18671&action=edit / https://sandbox.library.ucdavis.edu/career-block-changes-9-22/

**Comment by wrenaria** [comment]
A few changes to make:

### Cents
I only want to hide cents if there aren't any included in the figure / the figure reads .00, currently it hides cents all the time. Hourly wages, for example, likely need to include cents in the display. If that's not possible and it's all or nothing, then just keep the cents displayed at all times. 

### User-facing UI
Current line-height is too wide for paragraph-type content at this text size. Can we use **1.4 line-height** for the small text and also add **about 0.5 rem** between the description and the other metadata? 

![Screen Shot 2022-09-12 at 2 47 21 PM](https://user-images.githubusercontent.com/17831969/189764624-fe3c8c9a-e9c2-49a7-869b-53e44784cb24.png)

### Editor UI
Two "add" button/links is redundant. Keep one, remove the other (I don't care which one).

![Screen Shot 2022-09-12 at 2 42 00 PM](https://user-images.githubusercontent.com/17831969/189764644-d60bbce8-9ba9-4cc4-bd6d-0db785bd2b18.png)

**Comment by wrenaria** [comment]
We have an additional feature request to accommodate a currently unsupported HR need: some positions remain open until filled without a firm final filing date.

To support this, we will add an optional `open until filled` checkbox alongside the Filing Date selection area in the Careers Block editor UI. Checking the box would change the user-facing display to remove the word “final” and display additional text `for first consideration, open until filled` after the date (see mockup below). The box being checked would also keep the position displayed to users beyond the displayed filing date until someone manually removes it via the editor.

Mockup of user view with examples of a job that is open until filled + a job with a firm final filing date:

![career open until filled](https://user-images.githubusercontent.com/17831969/190730914-220b84d0-4fdc-4b36-8fb0-04dbf5987d7d.png)

**Comment by spelkey-ucd** [comment]
@UcDust we all good on this? can i close this issue?

**Comment by UcDust** [comment]
Yea this is complete, thanks for the reminder!
