### ISSUE TITLE
"Media & Text" Block missing space between text and image

### ISSUE THREAD

**Issue by wrenaria** [UCDavisLibrary/ucdlib-theme-wp#228]
No matter what spacing size I choose in the "Media & Text" block settings, when the image is set to be on the **right** side, there is no change to the space between the text and the image so they bump right into each other, but it adds space the right side of the text where I don't need it at all. This doesn't seem to be a problem for left side images. Is this something that can be fixed?

![Screen Shot 2022-11-09 at 3 24 34 PM](https://user-images.githubusercontent.com/17831969/200963794-20cb85bc-5ab0-418c-bc28-a3b4907bce82.png)

**Comment by spelkey-ucd** [comment]
@wrenaria Sorry for the delay in fixing this.

Spacing should be working for right side images now: https://sandbox.library.ucdavis.edu/media-text-block/

**Comment by wrenaria** [comment]
Yay for space! Thank you, looks good.

**Comment by spelkey-ucd** [comment]
Deployed `ucdlib-theme-wp v3.3.0`
