### ISSUE TITLE
Previewing edits to existing pages causes an error

### ISSUE THREAD

**Issue by wrenaria** [UCDavisLibrary/ucdlib-theme-wp#233]
When I try to preview changes to pages on the library website via the editor, it throws a "critical error." It seems to only happen when trying to preview drafts of existing pages, it doesn't do when if I start a new page and then try to preview it.

---

![Screen Shot 2023-01-18 at 5 04 29 PM](https://user-images.githubusercontent.com/17831969/213331534-80aa7295-2450-4702-97f3-673f2368e4e7.png)

![Screen Shot 2023-01-18 at 5 04 22 PM](https://user-images.githubusercontent.com/17831969/213331541-e8d61b7a-05f7-4212-a415-2fb0f67cd22a.png)

**Comment by spelkey-ucd** [comment]
Bug introduced when upgraded to php8.

It's an issue with Timber, that will be patched in their next release.
