### ISSUE TITLE
Add x-twitter icon

### ISSUE THREAD

**Issue by spelkey-ucd** [UCDavisLibrary/ucdlib-theme-wp#249]
https://fontawesome.com/icons/x-twitter?f=brands&s=solid

**Comment by spelkey-ucd** [comment]
@wrenaria I'll make sure the twitter x gets into our iconset, but the social share in the site footer uses a [sprite sheet](https://library.ucdavis.edu/wp-content/themes/ucdlib-theme-wp/assets/img/social-follow.svg) instead (because thats what patternlab does).

Can you update the sheet with the right logo and color?

**Comment by wrenaria** [comment]
Like so? https://drive.google.com/drive/folders/1UcpJOLaxrFM4nnQ79n1-GOQjR7nuVnQV?usp=sharing
