### ISSUE TITLE
Feature request: Recent News widget mixed format

### ISSUE THREAD

**Issue by wrenaria** [UCDavisLibrary/ucdlib-theme-wp#260]
The Recent News widget lets you display articles as a feature or as a teaser. Would you mind adding an option that does a combo? The first item in feature format, the rest in teaser?

Examples on Stage: https://stage.library.ucdavis.edu/news-widget/

Screenshot for posterity:

![Screenshot 2023-10-25 at 8 49 28 AM](https://github.com/UCDavisLibrary/ucdlib-theme-wp/assets/17831969/ac7c9fef-6aa4-4857-bd86-2b67b3dd3ef1)

**Comment by spelkey-ucd** [comment]
@wrenaria From a code perspective, it will be easier to add a "Start Offset" option where the list will start after x number of news items.

So you would use two news blocks, but second would have an offset of 1.

Is that okay?

**Comment by spelkey-ucd** [comment]
Added v3.6.0
