### ISSUE TITLE
Add icon: Julia logo

### ISSUE THREAD

**Issue by wrenaria** [UCDavisLibrary/ucdlib-theme-wp#287]
When you have time, please add this Julia logo to the available icon set in both DataLab and the library sites (DataLab is the priority for this). 

SVG: https://drive.google.com/file/d/1DrIdVDdIO-Udyi6VX-Ciil0papEma9Tx/view?usp=drive_link 

Thanks!

**Comment by spelkey-ucd** [comment]
released v4.0.0
