### ISSUE TITLE
Patterns: Remove "Lang Prize" patterns from core theme / show Patterns in dashboard

### ISSUE THREAD

**Issue by wrenaria** [UCDavisLibrary/ucdlib-theme-wp#291]
Please remove the theme-managed "lang prize" patterns that were created when dev-only patterns were a thing. The Lang Prize has its own section in the Library website patterns. The extras are creating confusion/muddling up the core theme patterns related to core text. 

They are titled:
- Lang Prize: Winner List
- Lang Prize: Winner Profile

![Screenshot 2024-06-18 at 3 20 39 PM](https://github.com/UCDavisLibrary/ucdlib-theme-wp/assets/17831969/4b606ee9-f26d-45c3-a208-6a3859dde356)

On a related note -- the Pattern management area shows up for me in the dashboard on Stage in Appearance > Patterns, but doesn't show in the production site dashboard. Any idea why? Are you able to fix that? The only way I can adjust patterns in production is pretty convoluted -- insert a pattern into a page and access the "manage patterns" from its local menu.

**Comment by spelkey-ucd** [comment]
released v4.0.0
