### ISSUE TITLE
Alignable Promo - Title and Subtitle display colors

### ISSUE THREAD

**Issue by wrenaria** [UCDavisLibrary/ucdlib-theme-wp#292]
In the new alignable promo block, The default coloration shows the title and subtitle in different colors, but the brand color versions show title and subtitle in the same coloration, making it impossible to differentiate between the two.

Is this the way it is intended to work? 

![Screenshot 2024-06-18 at 5 22 42 PM](https://github.com/UCDavisLibrary/ucdlib-theme-wp/assets/17831969/ad64f947-286a-48a7-bb3d-7f96c151d692)

**Comment by spelkey-ucd** [comment]
Yes, that is how it works: http://webstyleguide.ucdavis.edu/?p=organisms-branding-alignable-promo

**Comment by wrenaria** [comment]
Okay! What a weird choice by campus.
