### ISSUE TITLE
Auto recognize phone and email links?

### ISSUE THREAD

**Issue by wrenaria** [UCDavisLibrary/ucdlib-theme-wp#90]
Is it possible to have the Prefixed Icon Link block recognize telephone number and email address formats without needing to manually typing out the mailto: or tel: formats in the url area?

**Comment by wrenaria** [comment]
Related to this: I am running two other UX issues with Prefixed Icon Links.

1.  it's hard to tell if I've applied a link to it or not since it always **appears** linked even if there is no url associated. This is especially challenging with emails and phone numbers since they are not linking to other webpages so they are very easy to forget about.

2. Sometimes I want to format a contact item with an icon to match the Prefixed Link Icons but don't necessarily want to link it to anything (a room number, address or fax number, for example) -- _also: are fax numbers even html linkable?_

Is it possible to have the linking aspect be optional? If there is no associated URL just show the text part without link formatting / in plain text?

Example with fax # can be seen on the [ASC Harrison Collection](https://stage.library.ucdavis.edu/archives-and-special-collections/our-collections/michael-and-margaret-b-harrison-western-research-center-collection/)

**Comment by spelkey-ucd** [comment]
https://sandbox.library.ucdavis.edu/bug-fixes/#prefixed-icon-block
