### ISSUE TITLE
Shrink should cease shrinking at mobile sizes

### ISSUE THREAD

**Issue by wrenaria** [UCDavisLibrary/ucdlib-theme-wp#94]
Using [Visit and Study page on Stage](https://stage.library.ucdavis.edu/visit-study/) as an example, items using shrink are difficult to read at small sizes. At smaller scales, shrink should stop shrinking the content.

The [UC Davis Rankings page](https://www.ucdavis.edu/about/rankings) is an example of this in action with media links at the bottom of the page.

<img src="https://user-images.githubusercontent.com/17831969/162267206-082970be-e4b4-402b-b6cb-01ad546bf557.PNG" width="400">

**Comment by spelkey-ucd** [comment]
@wrenaria so the example from the uc davis site is a custom non-brand layout class (`body-constrained`) . However, I thought this might be an issue when I made the shrink block, so I built in the option to make the shrink full-width on mobile:
<img width="732" alt="image" src="https://user-images.githubusercontent.com/34284106/168320183-9de91bd0-a397-4821-bbf4-b0a0a866902e.png">

So, three questions for you:
1. does this solution work?
2. if it works, should the button be enabled by default (as of now, it is not)?
3. It is going full width at <480px. should i change that to a different breakpoint? 768px, 992px?

**Comment by wrenaria** [comment]
1. this is fine
2. enabled by default, I suspect 99% of the time, that is how we will want it to work. 
3. break at 768px

**Comment by spelkey-ucd** [comment]
https://sandbox.library.ucdavis.edu/bug-fixes/#shrink-in-mobile

**Comment by wrenaria** [comment]
Looks good!
