### ISSUE TITLE
Set "show hero image" to be the default

### ISSUE THREAD

**Issue by wrenaria** [UCDavisLibrary/ucdlib-theme-wp#97]
It will be rare (if ever) that we won't want a hero image to show on a page if there is one available to show. Please make UCD Theme Settings show the feature image by default. One less thing for people to remember to do (I forget almost every time until I look at my published page).

![Screen Shot 2022-04-25 at 12 00 48 PM](https://user-images.githubusercontent.com/17831969/165156242-cf9cfbf3-d8a1-47ae-ac10-7a45e0edaeed.png)

**Comment by spelkey-ucd** [comment]
'Show Hero Image' is now 'Hide Hero Image', and it is off be default.
https://sandbox.library.ucdavis.edu/bug-fixes/

**Comment by wrenaria** [comment]
Huzzah!
