### ISSUE TITLE
Brand Boxes and Branded Teasers show wrong heading colors on published page

### ISSUE THREAD

**Issue by wrenaria** [UCDavisLibrary/ucdlib-theme-wp#98]
Brand Boxes and Branded Teasers show wrong heading colors on published pages but appear to be correct in Editor view.

**Comment by spelkey-ucd** [comment]
https://sandbox.library.ucdavis.edu/bug-fixes/#branded-text-box

**Comment by wrenaria** [comment]
Looks good!
